package judge

import (
	"context"
	"fmt"

	"github.com/triageagent-dev/agentevals-go/internal/adk"
	"github.com/triageagent-dev/agentevals-go/internal/eval"
)

// rubricBasedFinalResponseQualityV1Prompt is byte-for-byte
// google-adk's rubric_based_final_response_quality_v1.py
// (_RUBRIC_BASED_FINAL_RESPONSE_QUALITY_V1_PROMPT). Placeholders, in
// Sprintf argument order: developer_instructions, tool_declarations,
// user_input, response_steps, final_response, rubrics.
const rubricBasedFinalResponseQualityV1Prompt = `SPECIAL INSTRUCTION: think silently. Silent thinking token budget: 10240 tokens.

# Mission
Your mission is to evaluate the final answer quality of responses generated by an AI agent. You will be presented with a user prompt (<user_prompt>), the agent's response (<response>) to that user prompt, and a set of properties (<property>) that you must use to objectively assess the validity of the agent's response.
Only respond to the properties provided. Do not make up new properties.

# Rubric
"yes": The model's response fulfilled the property, OR the property's condition was not applicable to the response.
"no": The model's response met the conditions for the property to be applicable, but failed to fulfill it, or the property applies to a claim in the model's response that cannot be unambiguously verified using trusted evidence.

# Key Evaluation Principles
Your evaluation must follow a two-part process: first, collect trusted evidence from the agent's work, and second, judge the final answer against it.
1. **Establish Trusted Evidence from Tool Calls**: You must first examine the agent's tool calls to determine if they are procedurally sound, meaning that the agent used the appropriate tools with logical parameters to address the user's prompt.
  * Your ONLY sources of truth are the <user_prompt> and the direct output ('tool_response') from PROCEDURALLY SOUND tool calls found in the <response_steps>. Examples of procedural flaws include:
    * The agent failed to call a tool that will enable it to answer the user's prompt despite having all the necessary parameters to do so.
    * The agent called the tool with incorrect or missing parameters.
    * The agent called a tool that does not exist, or called a tool with a parameter that does not exist.
    * The agent's sequence of tool calls contains a logical error.
  * The following kinds of information ABSOLUTELY CANNOT BE USED to derive trusted evidence:
    * The agent's final answer.
    * The agent's reasoning, summaries, or any interpretations of the tool responses by the agent.
    * Any tool call that is flawed (e.g., queries the wrong file, contains incorrect logic).
  * You may not have access to the same tools as the agent, so do not attempt to call any tools yourself.
2. **Judge Consistency with the Evidence**: Once you have collected trusted evidence from tool calls, you must determine whether the agent's <final_answer> is consistent with it. A claim in the final answer is only considered correct if it can be unambiguously verified using this evidence.
  * If the necessary evidence is missing because the agent failed to make a correct and sound tool call, the final answer must be judged as failing the property.

While judging the final answer against the evidence, be flexible about how it is conveyed. Accept answers that are semantically equivalent (e.g., different phrasing) as long as they still fulfill the property. For numbers, accept answers that are numerically equivalent, allowing for minor differences in rounding or precision, as long as they do not alter a final conclusion (e.g., the outcome of a statistical test).

For each property follow these internal steps:
1. Understand the property and the key evaluation principles.
2. Outline your plan to evaluate the property by applying the Key Evaluation Principles.
3. Collect and list the trusted evidence you will use to evaluate the property. Note any procedural flaws in the tool calls.
4. Judge the consistency of the final answer with the property and the trusted evidence.
5. Review your analysis from the previous steps to form a final judgment and determine the verdict.
6. Output the final verdict in the required output format.

# Output Format (repeat this format for every property, starting with a new line):
ID: [Copy the id shown in the "[id: ...]" tag for this property, verbatim. Omit this line only if no tag is shown.]
Property: [Repeat the property text that follows the "[id: ...]" tag, word for word, without making any changes and without the tag. Keep everything including punctuation and capitalization as-is.]
Evidence: [List all trusted evidence from tool calls or the user prompt that is relevant to the property (referencing the Step Index). Alternatively, if either no trusted evidence is required, or no trusted evidence exists (e.g., flawed process, missing tool call, tool error), explain why.]
Rationale: [Explain your reasoning, detailing how the evidence (or lack thereof) supports or contradicts the final answer, or why the property is not applicable.]
Verdict: [yes|no]

REMEMBER: Your answer will help improve the AI agent. It is important to determine the fulfillment of the properties correctly. Even answering "no" will improve the agent! Respond in pure text, not json.

# Example
## Input
<user_prompt>
  <developer_instructions>
  You are an AI agent who is an expert in HR data analysis.
  If a company has fewer than 100 employees, then the final answer should alert the user that there are fewer than 100 employees.
  If you have sufficient information and tools to respond to the user's question, then do not ask for further clarification.
  </developer_instructions>
  <available_tools>
  {
    'name': 'load_hr_data_from_file',
    'description': 'Reads a data file from the company's HR database into a Pandas DataFrame.'
    'parameters': [
        {
          'type': 'string',
          'name': 'file_name',
          'description': 'The name of the data file.'
        },
    ],
    'required': ['file_name']
  },
  {
    'name': 'get_manager',
    'description': 'Returns the manager of a given employee.',
    'parameters': [
        {
          'type': 'string',
          'name': 'employee_name',
          'description': 'The name of the employee.'
        },
    ],
    'required': ['employee_name']
  }
  </available_tools>
  <main_prompt>
  Using the employees.csv file, determine:
  1. the total number of employees
  2. the name of Alice Smith's manager
  3. the name of the employee with the highest salary, and their gender
  4. the average salary for the "Marketing" department
  Please format your final answer as a numbered list.
  </main_prompt>
</user_prompt>
<response>
  <response_steps>
  [
    {
      "step_index": 0,
      "tool_call": "df = load_hr_data_from_file('employees.csv')\nprint(len(df))",
      "tool_response": "110",
    },
    {
      "step_index": 1,
      "tool_call": "print(df[df['Department'] == 'Engineering']['Salary'].mean())",
      "tool_response": "155000",
    },
    {
      "step_index": 2,
      "tool_call="print(df.loc[df['Salary'].idxmax(), 'Name'])",
      "tool_response": "John Smith",
    },
  ]
  </response_steps>
  <final_answer>
  1. The total number of employees is 110.
  2. Please provide Alice Smith's employee ID so that I can find her manager.
  3. The employee with the highest salary is John Doe, and this employee's gender is male.
  4. The average salary for the Marketing department is 155000.
  </final_answer>
</response>

<properties>
*  [id: 1] The final answer correctly identifies the total number of employees.
*  [id: 2] The final answer correctly identifies the name of Alice Smith's manager, or correctly states that it cannot be determined and why.
*  [id: 3] The final answer correctly states the average salary for the Marketing department.
*  [id: 4] The final answer correctly identifies the employee with the highest salary.
*  [id: 5] The final answer correctly identifies the gender of the employee with the highest salary, or correctly states that it cannot be determined and why.
*  [id: 6] The final answer is formatted as a numbered list.
*  [id: 7] If the company has fewer than 100 employees, then the final answer states that it has fewer than 100 employees.
</properties>

## Output
ID: 1
Property: The final answer correctly identifies the total number of employees.
Evidence: The trusted evidence is "110 employees". The tool call in Step 0 is procedurally sound and provides the total number of employees (110) by calling the load_hr_data_from_file tool with the correct file name.
Rationale: The final answer's claim ("110 employees") is fully consistent with the trusted evidence.
Verdict: yes

ID: 2
Property: The final answer correctly identifies the name of Alice Smith's manager, or correctly states that it cannot be determined and why.
Evidence: No trusted evidence exists. The agent did not perform a tool call to determine the manager of Alice Smith, despite having the necessary information (the employee name) and access to the necessary tools (get_manager) to do so.
Rationale: The agent incorrectly stated that the final answer cannot be determined, despite having the necessary information (the employee name) and tools (get_manager) to determine it.
Verdict: no

ID: 3
Property: The final answer correctly states the average salary for the Marketing department.
Evidence: No trusted evidence exists for the Marketing department's average salary. The tool call in Step 1 is procedurally flawed; the agent searched for "Engineering" instead of "Marketing".
Rationale: There is no trusted evidence for the Marketing department's average salary.
Verdict: no

ID: 4
Property: The final answer correctly identifies the employee with the highest salary.
Evidence: The trusted evidence is "John Smith". The tool call in Step 2 produces trusted evidence for the employee with the highest salary by calling the load_hr_data_from_file tool with the correct file name and then using the idxmax() method to find the employee with the highest salary.
Rationale: The final answer's claim ("John Doe") is inconsistent with the trusted evidence ("John Smith").
Verdict: no

ID: 5
Property: The final answer correctly identifies the gender of the employee with the highest salary, or correctly states that it cannot be determined and why.
Evidence: No trusted evidence exists. The agent did not perform a tool call to determine the gender of the employee with the highest salary.
Rationale: There is no trusted evidence to confirm the gender of the employee with the highest salary that the final answer states (male). Even if the gender is coincidentally actually male, the claim in the final answer cannot be unambiguously verified using the evidence.
Verdict: no

ID: 7
Property: If the company has fewer than 100 employees, then the final answer should state that it has fewer than 100 employees.
Evidence: The trusted evidence is "110 employees". The tool call in Step 0 correctly counts the total number of employees as 110 by calling the load_hr_data_from_file tool with the correct file name.
Rationale: The total number of employees is 110, so the condition for this property (fewer than 100 employees) was not met. Therefore, the property is not applicable to this response.
Verdict: yes

ID: 6
Property: The final answer is formatted as a numbered list.
Evidence: N/A. Trusted evidence from tool calls or the user prompt is not required in order to determine the format of the final answer.
Rationale: The final answer is formatted as a numbered list from 1 to 4, e.g. "1. The total number of employees is 110\n2...".
Verdict: yes

# Your Turn
## Input
<user_prompt>
  <developer_instructions>
  %s
  </developer_instructions>

  <available_tools>
  %s
  </available_tools>

  <main_prompt>
  %s
  </main_prompt>
</user_prompt>

<response>
  <response_steps>
  %s
  </response_steps>
  <final_answer>
  %s
  </final_answer>
</response>

<properties>
%s
</properties>

## Output`

// rubricBasedToolUseQualityV1Prompt is byte-for-byte google-adk's
// rubric_based_tool_use_quality_v1.py
// (_RUBRIC_BASED_TOOL_USE_QUALITY_V1_PROMPT). Placeholders, in Sprintf
// argument order: tool_declarations, user_input, tool_usage, rubrics.
const rubricBasedToolUseQualityV1Prompt = "# Mission\n- Your mission is to evaluate the quality of responses generated by an AI agent. You will be presented with a user prompt (<user_prompt>), the agent's response (<response>) to that user prompt, and a set of properties (<property>) that you must use to objectively assess the validity of the agent's response.\n- Only use the properties provided. Do not make up new properties.\n- IMPORTANT: Assess all of the provided properties. Do not drop any of the properties from your response.\n- The primary focus of this rating task is to check correctness of the agent's responses w.r.t. each of the properties.\n\n# Rubric\n\"yes\": The agent's response fulfilled the property or the property is not applicable to the response.\n\"no\": The agent's response did not fulfill the property.\n\n# For each property started with a new line, follow these steps:\nSTEP 1: Repeat the property text (excluding the \"[id: ...]\" tag), word for word, without making any changes. Keep everything including punctuation and capitalization as-is.\nSTEP 2: Determine the steps needed to **exactly**, **precisely** and **completely** determine whether the agent's response fulfilled the property.\nSTEP 3: Follow the steps outlined in STEP 2, thinking out loud.\nSTEP 4: Review the thoughts and the original property.\nSTEP 5: Output the final verdict.\nID: [[Copy the id shown in the \"[id: ...]\" tag for this property, verbatim. Omit this line only if no tag is shown.]]\nProperty: [[Repeat the property in STEP 1 again, without the \"[id: ...]\" tag.]]\nRationale: [[Explain your reasoning for the verdict.]]\nVerdict: [[yes|no]]\n\n# Output format (repeat this format for every property started with a new line):\nSTEP 1: ...\nSTEP 2: ...\nSTEP 3: ...\nSTEP 4: ...\nSTEP 5: ...\nID: ...\nProperty: ...\nRationale: ...\nVerdict: ...\n\n\n# Example output 1\n\nSTEP 1: Does the agent run function call 'default_api.grammar_check'?\nSTEP 2: I need to check if the agent runs the function call with exact function name as 'default_api.grammar_check'.\nSTEP 3: The response includes a function call 'default_api.grammar_check'.\nSTEP 4: The function call format and the function name are correct.\nSTEP 5: yes\nID: 1\nProperty: Does the agent run function call 'default_api.grammar_check'?\nRationale: The agent's response contains the function call 'default_api.grammar_check' within a proper code block and with the correct function name.\nVerdict: yes\n\nSTEP 1: Does the agent provide function call 'default_api.grammar_check' with input parameter 'sentence' that is valid compared to the reference 'sentence'= 'the dog walks on the a park' and based on the following guideline? Guideline for 'sentence': 'The wording can differ. The agent response is valid if it conveys similar core content as the reference response. Less efficient and minor inaccurate phrasing is acceptable. The default value is None, if the reference response includes this parameter with value equal to the default value but it is not provided in the agent response, then evaluate it as valid.'\nSTEP 2: I need to check if the function call 'default_api.grammar_check' includes the parameter 'sentence' and whether the value assigned to 'sentence' is valid according to the provided guideline. The reference value is 'the dog walks on the a park'. According to the guideline, the wording can differ as long as the core content is similar.\nSTEP 3: The agent's response includes the function call `default_api.grammar_check(sentence=\"the dog walks on the a park\")`. The parameter 'sentence' is present, and the value assigned to it is \"the dog walks on the a park\", which is identical to the reference value.\nSTEP 4: The parameter 'sentence' is present and its value is exactly the same as the reference value.\nSTEP 5: yes\nID: 2\nProperty: Does the agent provide function call 'default_api.grammar_check' with input parameter 'sentence' that is valid compared to the reference 'sentence'= 'the dog walks on the a park' and based on the following guideline? Guideline for 'sentence': 'The wording can differ. The agent response is valid if it conveys similar core content as the reference response. Less efficient and minor inaccurate phrasing is acceptable. The default value is None, if the reference response includes this parameter with value equal to the default value but it is not provided in the agent response, then evaluate it as valid.'\nRationale: The agent's response includes the 'sentence' parameter in the function call 'default_api.grammar_check', and the value assigned to it is exactly the same as the reference value, thus satisfying the given guideline.\nVerdict: yes\n\n# Example output 2\n\nSTEP 1: Does the agent run function call 'default_api.search_via_perplexity'?\nSTEP 2: I need to check if the agent runs the function call with exact function name as 'default_api.search_via_perplexity'.\nSTEP 3: The response includes a function call `default_api.get_web_search_results`, which does not match 'default_api.search_via_perplexity'.\nSTEP 4: The function name does not match.\nSTEP 5: no\nID: 1\nProperty: Does the agent run function call 'default_api.search_via_perplexity'?\nRationale: The agent called 'default_api.get_web_search_results', not 'default_api.search_via_perplexity'.\nVerdict: no\n\nSTEP 1: Does the agent provide function call 'default_api.search_via_perplexity' with input parameter 'keyword' that is valid compared to the reference 'keyword'= 'GPT-4o vs GPT-3.5 cost comparison' and based on the following guideline? Guideline for 'keyword': 'The wording can differ. The agent response is valid if it conveys similar core content as the reference response. Less efficient and minor inaccurate phrasing is acceptable.'\nSTEP 2: Since the previous property is no, this property is not applicable.\nSTEP 3: N/A\nSTEP 4: N/A\nSTEP 5: yes\nID: 2\nProperty: Does the agent provide function call 'default_api.search_via_perplexity' with input parameter 'keyword' that is valid compared to the reference 'keyword'= 'GPT-4o vs GPT-3.5 cost comparison' and based on the following guideline? Guideline for 'keyword': 'The wording can differ. The agent response is valid if it conveys similar core content as the reference response. Less efficient and minor inaccurate phrasing is acceptable.'\nRationale: The agent did not use the function call 'default_api.search_via_perplexity'.\nVerdict: yes\n\n\n# Available tools, user input, response and properties:\n<available_tools>\n%s\n</available_tools>\n\n<user_prompt>\n%s\n</user_prompt>\n\n<response>\n%s\n</response>\n\n<properties>\n%s\n</properties>\n\nREMEMBER: Your answer will help improve the AI agent. It is important to determine the fulfillment of the properties correctly. Even answering \"no\" will improve the agent! Respond in pure text, not json.\nIMPORTANT: Make sure for each of the property listed, follow the example steps and output \"Property: ...\" on a new line and \"Verdict: ...\" on another new line."

// formatRubricBasedFinalResponseQualityV1Prompt ports
// RubricBasedFinalResponseQualityV1Evaluator.format_auto_rater_prompt.
// developer_instructions is always "" and tool_declarations is always
// "Agent has no tools." in this port, since our adk.Invocation has no
// app_details equivalent (same simplification as hallucinations_v1 and
// runMultiTurnMetric's synthesized single-agent schema - see
// vertexeval.collectToolNames). include_intermediate_responses_in_final
// is left at its google-adk default (false), matching
// final_response_match_v2's own choice.
func formatRubricBasedFinalResponseQualityV1Prompt(actual adk.Invocation, rubrics []Rubric) string {
	userInput := actual.UserContent.Text()
	finalResponse := actual.FinalResponse.Text()
	responseSteps := toolCallsAndResponsesText(actual.IntermediateData)
	rubricsText := formatRubricsText(rubrics)
	return fmt.Sprintf(
		rubricBasedFinalResponseQualityV1Prompt,
		"", "Agent has no tools.", userInput, responseSteps, finalResponse, rubricsText,
	)
}

// RubricBasedFinalResponseQualityV1 scores each actual invocation's final
// response against caller-supplied rubrics (there is no built-in rubric
// set - see RubricsFromStrings), sampling the judge model numSamples
// times per invocation and majority-voting each rubric, then averaging
// every (invocation, rubric) score across the whole trace. Ported from
// RubricBasedFinalResponseQualityV1Evaluator (via RubricBasedEvaluator /
// LlmAsJudge).
func RubricBasedFinalResponseQualityV1(ctx context.Context, model Model, actual []adk.Invocation, rubrics []Rubric, numSamples int, threshold float64) (eval.Result, error) {
	return runRubricMetric(ctx, model, "rubric_based_final_response_quality_v1", actual, rubrics, numSamples, threshold,
		func(inv adk.Invocation) string {
			return formatRubricBasedFinalResponseQualityV1Prompt(inv, rubrics)
		},
	)
}

// formatRubricBasedToolUseQualityV1Prompt ports
// RubricBasedToolUseV1Evaluator.format_auto_rater_prompt.
// tool_declarations is always "Agent has no tools." in this port (see
// formatRubricBasedFinalResponseQualityV1Prompt).
func formatRubricBasedToolUseQualityV1Prompt(actual adk.Invocation, rubrics []Rubric) string {
	userInput := actual.UserContent.Text()
	toolUsage := toolCallsAndResponsesText(actual.IntermediateData)
	rubricsText := formatRubricsText(rubrics)
	return fmt.Sprintf(
		rubricBasedToolUseQualityV1Prompt,
		"Agent has no tools.", userInput, toolUsage, rubricsText,
	)
}

// RubricBasedToolUseQualityV1 scores each actual invocation's tool usage
// against caller-supplied rubrics; see RubricBasedFinalResponseQualityV1
// for the shared sampling/aggregation behavior. Ported from
// RubricBasedToolUseV1Evaluator.
func RubricBasedToolUseQualityV1(ctx context.Context, model Model, actual []adk.Invocation, rubrics []Rubric, numSamples int, threshold float64) (eval.Result, error) {
	return runRubricMetric(ctx, model, "rubric_based_tool_use_quality_v1", actual, rubrics, numSamples, threshold,
		func(inv adk.Invocation) string {
			return formatRubricBasedToolUseQualityV1Prompt(inv, rubrics)
		},
	)
}
