apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:HALDKEJEC+KI7fYlsUV4oX8AkkTZnAmd8B0IA57jsF7HbVTKWX2YuKJEsEah7JLTIhHMxIxLuzH3QMZm5e7lyi2r6qDAfkoVqpL0XXT5PahB+BLvpyB3gC9RVTa3u6kKq95inQ==,iv:WLZxhnziD+QVryMIwL4ih0j8s8EGTgyNkwm0bELxvXI=,tag:Tzhl4LUQvOIfHfNDOkQOLQ==,type:str]
kind: Secret
metadata:
    name: xray-memory-snapshot-key
    namespace: xray-memory
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVFlTi9xYnorbEtSLy9p
            UTZsaDB2SE81NUxnWnZud3dWZjcwRVJCcUJVCmM0dnBWU1R6VWdqaGhEYVNRTnV5
            VTJFWmxNTXk5S1RRUllpSHMwb3l5RkUKLS0tIFRxUktOMmlKSHFEUmR3NVp5QWRK
            endFTW9EYmZQOTVFN05pd1Bvd21lbm8K2b13lujBfzHjes18thK9CBlVlkQUqp0w
            cau5nZS50DxZLBCsfpWoN2ly0bTv/dg7aWVOrj2jNGf32UktSDQ9Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14yx8fu34xgpvs50z8tehjvlx04c6cslssujszd6zwf8ln2cscdyq4hsc5t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T16:05:08Z"
    mac: ENC[AES256_GCM,data:3laNpI3LqtWp7K3NkMEo5dp8Ymk0EgNBQKLO6Vqv4A1ed40rrPiL5XIAm6Wac3++B09mFwQJUzMAmdPPHXFOcqgsq0BMYfqDm0tVeSuxPxXvs7thxbYWar4H+KtOyWVXvOeiBTkdTgfk3jpLVzEZRqQPk/jANtsxMsm7rdmV0BU=,iv:W3tnn3N2ML1Sg/m1iHeuN4XZW1BQHUz+eMk667aVLzM=,tag:hLI7DlPU3AXEONSsc48t2Q==,type:str]
    version: 3.13.3
